name: foldable_list
description: An animated foldable list with expanded items that will be shown when user click on a cell
version: 1.0.0
homepage: https://github.com/koukibadr/Foldable-List

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
